### ISSUE TITLE
struct.error: unpack requires a buffer of 112 bytes

### ISSUE THREAD

**Issue by markddavidoff** [jamesbowman/i2cdriver#45]
```
>>> i2cdriver.I2CDriver("/dev/tty.usbserial-DO02C6S9").scan()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/i2cdriver.py", line 188, in scan
    d = struct.unpack("112c", self.ser.read(112))
struct.error: unpack requires a buffer of 112 bytes
```

**Comment by markddavidoff** [comment]
can no longer repro /shrug
